// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAkEwbyoSpzn96Xqxlrpih-97vvio7MT68',
    appId: '1:559145442622:web:dbd756ef7d88e23636a06f',
    messagingSenderId: '559145442622',
    projectId: 'auth-8ba19',
    authDomain: 'auth-8ba19.firebaseapp.com',
    storageBucket: 'auth-8ba19.appspot.com',
    measurementId: 'G-74DWK2YPN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAi3Py2t9c4nTh30NAJ5K8dmVq3ssZz1EE',
    appId: '1:559145442622:android:6236ac51e37c607436a06f',
    messagingSenderId: '559145442622',
    projectId: 'auth-8ba19',
    storageBucket: 'auth-8ba19.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD7n_lcHtpHT4PVNrP7aFFtUdLtjUsWYZo',
    appId: '1:559145442622:ios:74bc7b3ecdc78f8936a06f',
    messagingSenderId: '559145442622',
    projectId: 'auth-8ba19',
    storageBucket: 'auth-8ba19.appspot.com',
    iosClientId: '559145442622-eeh8gdaf3ft7p60ioj76osmd36d1kmg1.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuranWords',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7n_lcHtpHT4PVNrP7aFFtUdLtjUsWYZo',
    appId: '1:559145442622:ios:48141b8f9cbb5f7436a06f',
    messagingSenderId: '559145442622',
    projectId: 'auth-8ba19',
    storageBucket: 'auth-8ba19.appspot.com',
    iosClientId: '559145442622-t6dbjdbi9ojfff14vtp4qitvfsjh4g7g.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterQuranWords.RunnerTests',
  );
}
